### ISSUE TITLE
"Oops, something went wrong" error when signing in with Google

### ISSUE THREAD

**Issue by seannymurrs** [capnslipp/ChatGPT-iOS#3]
Currently, my ChatGPT account is set up to sign in with Google. When I try and do that in the app, it jumps over to Safari to sign in. After I choose my Google account, and go through the 2-factor authentication, I get an, "Oops, something went wrong..." error from OpenAI. I tried following their suggestions of clearing cookies and using private browsing mode, but am still getting the error. I tried using a different account that uses the standard username/password login, and that one worked fine.

**Comment by capnslipp** [comment]
Should be fixed now.  Please verify.
